### ISSUE TITLE
Future of preos and __install_* types

### ISSUE THREAD

**Issue by sideeffect42** [skonfig/skonfig#1]
The supported operating systems and CPU architectures of PreOS and associated `__install_*` types are limited and have not improved.
Only some of cdist's users actually use this feature. As such I don't think it should have a place in cdist's core.

What should we do with it?

**Comment by 4nd3r** [comment]
I would leave related code in core as-is for now, but move `__install_*` types to museum.

**Comment by sideeffect42** [comment]
PR to move `__install` types (cf. cdist-community/cdist-conf#48 and [cdist-community/__install](/cdist-community/__install)).
