### ISSUE TITLE
Repo tagging

### ISSUE THREAD

**Issue by 4nd3r** [skonfig/skonfig#36]
This `skonfig` repo contains 176 tags from cdist-era.

Option 1: delete all the tags.
Option 2: rename cdist-era tags to `cdist/<tag>`.
Option 3: ???

I think we should keep cdist version tags for historical accuracy, but I'm not sure how this tag renaming should work. I would just re-tag all tagged commits with new tag and then remove old tags.  This might screw up other peoples local repos when they pull. If anyone has better idea, please don't hold yourself back.

**Comment by sideeffect42** [comment]
Agreed, we should clean the tags. My gut feeling says that renaming the tags would be the best solution.

> This might screw up other peoples local repos when they pull.

How would it do so? I'd expect you just get a lot of "deleted tag"/"new tag" messages and in the worst case end up with a detached HEAD (but you have a detached HEAD anyway when you check out a tag).

IIRC cdist signed some/all(?) of the tags. Can we rename them without breaking the signature?
Or don't we care if the signature is broken?

**Comment by 4nd3r** [comment]
You can't exactly rename tag, but I did something. `git pull --prune --tags` should clean up your local repo.
