### ISSUE TITLE
Benefits of use_archiving

### ISSUE THREAD

**Issue by 4nd3r** [skonfig/skonfig#42]
Continuation of https://github.com/skonfig/skonfig/pull/40#discussion_r958531319

According to `cdist/argparse.py`:
```
# set of beta sub-commands
BETA_COMMANDS = set(('install', 'inventory', 'scan', ))
# set of beta arguments for sub-commands
BETA_ARGS = {
    'config': set(('tag', 'all_tagged_hosts', 'use_archiving', )),
}
```

We currently use "use_archiving".

I think I did some tests back then (when Darko implemented it) and discovered that `archiving: tar` has positive effect. But tgz, tbz2 and txz did not give much extra (maybe because I have `Compression yes` in `~/.ssh/config`) and I noticed weird lockups when I had to move big binary files.

**Comment by sideeffect42** [comment]
I updated the issue title because all the other beta stuff was removed in #43, #44, #57, #63.

**Comment by 4nd3r** [comment]
Is there anything left to discuss here? I think we can close it, because we find archiving feature useful. Feel free to reopen it, tho.
